version: '3.8'
services:
  structure-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=slow
      - MYSQL_DATABASE=slow
      - MYSQL_USER=slow
      - MYSQL_PASSWORD=slow

  structure-adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      - ADMINER_DESIGN=flat
