version: '3.8'
services:
  structure-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db

  structure-adminer:
    image: adminer:latest
    ports:
      - 8082:8080
    environment:
      - ADMINER_DESIGN=flat
