version: '3.8'
services:
  slow-db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=slow
      - MYSQL_DATABASE=slow
      - MYSQL_USER=slow
      - MYSQL_PASSWORD=slow
  fast-db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=fast
      - MYSQL_DATABASE=fast
      - MYSQL_USER=fast
      - MYSQL_PASSWORD=fast
